### PR TITLE
Fix errored cell notification

### LINKED ISSUE #10: Notification is not triggered when the cell has an error.
In the current implementation, notification is triggered by `NotebookActions.executed` signal. Unfortunately, this signal seems not to be emitted when the cell has any exceptions.

Although I don't have any idea how to fix the issue, I think it's natural to want to know as soon as possible when an error occurs.

## example

I set notification threshold 3 sec:

```
{
    "minimum_cell_execution_time": 3,
}
```

And, I confirmed that the following code worked.

```
!sleep 3
print("hello world!")
```

With the same configuration, I tried the following code.

```
!sleep 3
raise ValueError("fail")
```

### PR DESCRIPTION
**Pull request by mwakaba2**
Fixes #10 

This change will allow browser notifications for failed cell executions. Users will no longer need to enable `recordTiming`.
Screen Shot 2021-07-11 at 1 28 33 PM

# Todo

- [x] Add the error notification image to the readme

@i-aki-y I'd appreciate your review!

### CODE REVIEW

**Comment by i-aki-y** [comment]
Thanks @mwakaba2 , it's great!

LGTM! I could confirm it works in my environment.

**Review by i-aki-y — DISMISSED** [review]

File: src/index.ts [hunk 1]
```diff
@@ -46,20 +41,62 @@ function displayNotification(
...
+  failedExecution: boolean,
+  error: KernelError | null
+) {
+  const codeCell = cell.model.type === 'code';
+  const nonEmptyCell = cell.model.value.text.length > 0;
+  const codeCellModel = cell.model as ICodeCellModel;
+
+  if (codeCell && nonEmptyCell) {
+    const diff = new Date(<any>cellEndTime - <any>cellStartTime);
+    if (diff.getSeconds() >= minimumCellExecutionTime) {
```
Comment (i-aki-y) [inline src/index.ts]: This makes the same issue in #16.

Comment (mwakaba2) [reply src/index.ts]: Thanks for catching that! I think I resolved some of the merge conflicts incorrectly, so I'll make sure all the latest fixes are there.
