### PR TITLE
Track cell start and end times in a metadata object

### LINKED ISSUE #23: The `cellStartTime` is overwritten with multiple executions.
Thanks to introducing the `executionScheduled` signal, we can now calculate the duration time more flexibly.
But in the current version, the `cellStartTime` is shared between multiple cell executions, so the `cellStartTime` can be overwritten by the latest execution.
This might cause some unexpected behaviors, see the following example.

### Example

Now, let assume the following settings and cells:

```
# settings
{
    "minimum_cell_execution_time": 3,
}
```

```
# cells
Cell [1]: !sleep 4
Cell [2]: !sleep 2
````

Consider running the two cells in the following steps:

1. run the cell [1].
2. wait 2 seconds.
3. run the cell [2].
 
In this case, I expect that a notification is issued just after completing the cell [1]. But no notification is given because the cell [2] execution overwrites the `cellStartTime` and the duration time of the cell [1] becomes to be less than 2 seconds.

### Workaround idea

I think a simple workaround is to introduce a table that has mappings from cells to their cellStartTimes and replace `cellStartTime` with `cellStartTimeTable[cell.id]` or something.
Note this is a just idea, so there may be non-trivial problems.

### PR DESCRIPTION
**Pull request by mwakaba2**
fixes #23 

@i-aki-y I created a draft to fix the overwritten start time issue. As suggested, this uses a table that keeps track of both the start and end time for the executed cells. It also deletes them, once the notification is complete.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -113,23 +114,24 @@ const extension: JupyterFrontEndPlugin<void> = {
       setting.changed.connect(updateSettings);
     }
 
-    let cellStartTime = new Date();
-
     NotebookActions.executionScheduled.connect((_, args) => {
+      const { cell } = args;
       if (enabled) {
-        cellStartTime = new Date();
+        cellExecutionTimeMetadata[cell.model.id] = { startTime: new Date(), endTime: new Date() };
```
Comment (mwakaba2) [inline src/index.ts]: I tried to use `cell.id` to get the cell's unique identifier, but it looks like it's undefined. I was able to get the id from
`cell.model.id`. I created a bug report on Jupyterlab: https://github.com/jupyterlab/jupyterlab/issues/10697

**Comment by mwakaba2** [comment]
This is still WIP.
I noticed two things I need to fix:

- When several cells are scheduled at the same time, the cell duration is (cell end time - scheduled time), not (cell end time - cell actual start time).
- When several cells are scheduled at the same time, the cell index number == the last cell index number.

**Comment by mwakaba2** [comment]
This is ready for review!
I created two additional notebooks to test executing 3 in parallel. 
I ran the following cells at the same time and confirmed that each cell's index and duration are correct:

* first two cells in `py3_demo.ipynb`
* all cells in `py3_demo_2.ipynb`
* all cells in `py3_demo_3.ipynb`

File: src/index.ts [hunk 2]
```diff
@@ -113,30 +126,44 @@ const extension: JupyterFrontEndPlugin<void> = {
...
+        const notebookId = notebook.id;
+        const scheduledTime = cellExecutionMetadataTable[cellId].scheduledTime;
+        const recentExecutedCellTime =
+          recentNotebookExecutionTimes[notebookId] || scheduledTime;
+        cellExecutionMetadataTable[cellId].startTime =
+          scheduledTime >= recentExecutedCellTime
+            ? scheduledTime
+            : recentExecutedCellTime;
+        cellExecutionMetadataTable[cellId].endTime = cellEndTime;
+        recentNotebookExecutionTimes[notebookId] = cellEndTime;
```
Comment (mwakaba2) [inline src/index.ts]: it may be worth using an in-memory lru cache like https://www.npmjs.com/package/lru-cache to limit the number of notebook execution times.

Comment (mwakaba2) [reply src/index.ts]: decided to use lru-cache for `recentNotebookExecutionTime`.

File: src/index.ts [hunk 3]
```diff
@@ -96,6 +103,13 @@ const extension: JupyterFrontEndPlugin<void> = {
     let reportCellExecutionTime = true;
     let reportCellNumber = true;
     let cellNumberType = 'cell_index';
+    const cellExecutionMetadataTable: {
+      [cellId: string]: ICellExecutionMetadata;
+    } = {};
+    const recentNotebookExecutionTimes: LRU<string, Date> = new LRU({
+      max: 500,
+      maxAge: 1000 * 60 * 60 * 10 // 10 hours
```
Comment (i-aki-y) [inline src/index.ts]: There are some use-cases, like training a deep-learning model, that can take multiple days for execution.
It is difficult to estimate an appropriate maxAge in advance, so if there are no negative consequences to not setting the `maxAge`, why not leave `maxAge` unset?

File: src/index.ts [hunk 4]
```diff
@@ -96,6 +103,13 @@ const extension: JupyterFrontEndPlugin<void> = {
     let reportCellExecutionTime = true;
     let reportCellNumber = true;
     let cellNumberType = 'cell_index';
+    const cellExecutionMetadataTable: {
+      [cellId: string]: ICellExecutionMetadata;
+    } = {};
```
Comment (i-aki-y) [inline src/index.ts]: When a user deletes a running cell before its completion, the scheduled items remain in the `cellExecutionMetadataTable`.
How about using the LRU cache for `cellExecutionMetadataTable` as well?

**Review by i-aki-y — COMMENTED** [review]
@mwakaba2  Thank you for your solution. I put some comments.

File: src/index.ts (hunk 3 above)
Comment (mwakaba2) [reply src/index.ts]: yeah I think not setting `maxAge` is fine since least recently used items will be removed anyway.

File: src/index.ts (hunk 4 above)
Comment (mwakaba2) [reply src/index.ts]: mmh yeah that can happen. yep, an LRU cache makes sense here too. I'm thinking it maybe enough to allow storing 500 notebooks * 5 cells = 2,500 items at max?

Comment (i-aki-y) [reply src/index.ts]: yeah, I agree.

**Comment by mwakaba2** [comment]
I made several new changes:

* Convert cellExecutionMetadataTable into lru-cache
* I switched to momentjs for time diff calculations because the original logic wasn't calculating diff correctly if the difference was more than a day.

I'm going to merge this and make a release. 
I tested the new code changes by running the following cells at the same time and confirmed that each cell's index and duration are correct:

* first two cells in py3_demo.ipynb
* all cells in py3_demo_2.ipynb
* all cells in py3_demo_3.ipynb

I also created a github issue to create unit tests to catch any superfluous errors.
